### PR TITLE
fix: only show the setup wizard on 1st start

### LINKED ISSUE #118: Onboarding is too eager
I moved to a new laptop and quickly installed all the extensions that I might need for a variety of projects. I didn't have time to setup Ollama or finish the onboarding process yet, so I just closed the onboarding.

I opened a second VS Code window for a different project -> onboarding appears again and needs to be cancelled.

VS Code update -> both windows have onboard again and need to be cancelled.

My Mac rebooted -> both windows have onboarding again.

Opened a third window to look at another repo -> onboarding. Cancel it, open the folder for the repo -> onboarding. _Disable the extension until I'm ready to use it..._

Compared to other extensions it is just too frequent and in your face, and takes two clicks to cancel. The trigger should be less frequent/not every change, should have options to delay, or should just use notifications after the first time as most other extensions do.

### PR DESCRIPTION
**Pull request by fbricon**
## Description

- only show the setup wizard on 1st start
- don't use a modal dialog when closing an incomplete wizard

Fixes https://github.com/Granite-Code/granite-code/issues/118

## Screenshots
When run in dev mode (the running extension id is Continue)

Screenshot 2025-05-14 at 14 04 23

## Testing instructions

- close VS Code
- delete the global workspace for the extension you're testing, e.g. on Mac:

> sqlite3 ~/Library/Application\ Support/Code/User/globalStorage/state.vscdb 'delete from ItemTable where key="Continue.continue";'

or 

> sqlite3 ~/Library/Application\ Support/Code/User/globalStorage/state.vscdb 'delete from ItemTable where key="redhat.granitecode";'

- reopen VS Code, the wizard should show up. Restart VS Code, it won't show then.
- try closing the wizard before it's complete, you should see the aforementioned non-modal notification.

### CODE REVIEW

File: extensions/vscode/src/activation/activate.ts [hunk 1]
```diff
@@ -52,14 +52,19 @@ export async function activateExtension(context: vscode.ExtensionContext) {
...
-    !showOnboarding,
+    graniteOnboardingComplete,
   );
-  if (showOnboarding) {
-    await vscode.commands.executeCommand("granite.setup");
+
+  if (!graniteOnboardingComplete) {
+    const showOnboardingAtStartup = context.globalState.get("initialSetup", true);
+    if (showOnboardingAtStartup) {
+      await context.globalState.update("initialSetup", !showOnboardingAtStartup);
```
Comment (owtaylor) [inline extensions/vscode/src/activation/activate.ts]: Can you make this another constant in `core/granite/commons/constants.ts`? It's weird to me to have two things in globalState that are uncoordinated and in different places. Would be good to briefly (one-line) document their meaning - we can't rename `showGraniteOnboardingCard` but it doesn't really mean what it says any more.

Also, I think if graniteOnboardingComplete is set we should *still* clear the initialSetup variable.

File: extensions/vscode/src/granite/panels/setupGranitePage.ts [hunk 2]
```diff
@@ -83,17 +83,12 @@ export class SetupGranitePage {
...
-            "Resume Granite.Code Setup?",
-            {
-              modal: true,
-              detail:
-                "Granite.Code needs to be setup before it can be used. Setup is not yet complete.",
-            },
-            RESUME_LABEL, // Cancel is always shown
+          const REOPEN_LABEL = "Open Setup";
+          const choice = await window.showInformationMessage(
+            "Granite.Code setup incomplete",
```
Comment (owtaylor) [inline extensions/vscode/src/granite/panels/setupGranitePage.ts]: Let's make this "Granite.Code setup is incomplete"

**Review by owtaylor — CHANGES_REQUESTED** [review]
This seems mostly fine to me, just a few tweaks.

Should we show the notification on startup? - I suppose that could be annoying as well, but we *do* want people to actually try out the thing they installed.  (Hmm, are we adding the status bar item when setup is incomplete? That probably needs a warning icon and maybe could be another reentry point.)

File: extensions/vscode/src/granite/panels/setupGranitePage.ts (hunk 2 above)
Comment (fbricon) [reply extensions/vscode/src/granite/panels/setupGranitePage.ts]: done

File: extensions/vscode/src/activation/activate.ts (hunk 1 above)
Comment (fbricon) [reply extensions/vscode/src/activation/activate.ts]: done (I think ;-))

File: extensions/vscode/src/activation/activate.ts [hunk 3]
```diff
@@ -52,14 +53,23 @@ export async function activateExtension(context: vscode.ExtensionContext) {
...
     "granite.initialized",
-    !showOnboarding,
+    graniteOnboardingComplete,
   );
-  if (showOnboarding) {
-    await vscode.commands.executeCommand("granite.setup");
+
+  const showOnboardingAtStartup = !context.globalState.get<boolean>(GRANITE_INITIAL_ACTIVATION_COMPLETED_KEY, false);
+  if (graniteOnboardingComplete) {
+    if (!showOnboardingAtStartup) {
```
Comment (owtaylor) [inline extensions/vscode/src/activation/activate.ts]: This is backwards, I think

File: extensions/vscode/src/activation/activate.ts [hunk 4]
```diff
@@ -52,14 +53,23 @@ export async function activateExtension(context: vscode.ExtensionContext) {
...
+      await context.globalState.update(GRANITE_INITIAL_ACTIVATION_COMPLETED_KEY, true);
+    }
+  } else {
+    if (showOnboardingAtStartup) {
+      await context.globalState.update(GRANITE_INITIAL_ACTIVATION_COMPLETED_KEY, true);
+      await vscode.commands.executeCommand("granite.setup");
+    }
```
Comment (owtaylor) [inline extensions/vscode/src/activation/activate.ts:67]: What about:

```ts
const initialActivationCompleted = context.globalState.get<boolean>(GRANITE_INITIAL_ACTIVATION_COMPLETED_KEY, false);
if (!initialActivationCompleted) {
  if (!graniteOnboardingComplete) {
          await vscode.commands.executeCommand("granite.setup");;
  }
  await context.globalState.update(GRANITE_INITIAL_ACTIVATION_COMPLETED_KEY, true);
}
```
The fact that `showOnboardingAtStartup` is reversed from the key makes it hard for me to follow.

File: core/granite/commons/constants.ts [hunk 5]
```diff
@@ -1,4 +1,9 @@
 export const isDevMode = process.env.CONTINUE_DEVELOPMENT === "true";
 export const isTestMode = process.env.CONTINUE_GLOBAL_DIR?.includes("e2e/test");
 
-export const SHOW_GRANITE_ONBOARDING_CARD_KEY = "showGraniteOnboardingCard";
+//Despite its name, this key is now used to track whether the user has completed the onboarding flow
+// showGraniteOnboardingCard===true means the user has completed the onboarding flow
+export const GRANITE_ONBOARDING_INCOMPLETE_KEY = "showGraniteOnboardingCard";
+
+// This key is used to track whether the user has running the initial activation flow
```
Comment (owtaylor) [inline core/granite/commons/constants.ts]: s/has running/has run/

File: extensions/vscode/src/granite/panels/setupGranitePage.ts [hunk 6]
```diff
@@ -1,32 +1,32 @@
 import { LocalModelSize } from "core";
 import { ConfigHandler } from "core/config/ConfigHandler";
 import {
-  DEFAULT_MODEL_GRANITE_LARGE,
-  DEFAULT_MODEL_GRANITE_SMALL,
+    DEFAULT_MODEL_GRANITE_LARGE,
+    DEFAULT_MODEL_GRANITE_SMALL,
```
Comment (owtaylor) [inline extensions/vscode/src/granite/panels/setupGranitePage.ts]: Hmm, why the spaces added here? Did your identation settings get confused somehow?

Comment (fbricon) [reply extensions/vscode/src/granite/panels/setupGranitePage.ts]: no idea what happened. It fixed itself next time I saved.

File: extensions/vscode/src/activation/activate.ts (hunk 4 above)
Comment (fbricon) [reply extensions/vscode/src/activation/activate.ts:67]: Sorry not sure I how got to that mess, your solution is 100% better

**Comment by fbricon** [comment]
updated

**Review by owtaylor — APPROVED** [review]
