### PR TITLE
Fix disk space check when selecting model

### LINKED ISSUE #58: Diskspace analysis isn't working right
On my (linux) system I have this config:

```
╎❯ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3  1.9T  1.8T  116G  94% /sysroot
/dev/nvme0n1p2  974M  161M  746M  18% /boot
/dev/nvme0n1p3  1.9T  1.8T  116G  94% /var/home
/dev/nvme0n1p1  599M   47M  553M   8% /boot/efi
```

So you can see both the system root and the home directory use the same underlying device, but are separate btrfs subvolumes.
This is a pretty standard set up in Fedora silverblue.

Now the problem is the setup wizard doesn't think I have enough disk space to download the granite models:

Image

There is more than one bug here, but the most fundamental issue is it is checking for available space on the system root, not the directory where ollama models get downloaded.

```
export async function getSystemDiskSpace(): Promise<DiskSpace> {
  try {
    const fsSize = await si.fsSize();
    const mainVolume = fsSize.find((drive) =>
      process.platform === "win32"
        ? drive.mount.toLowerCase().includes("c:")
        : drive.mount === "/",
    );
    if (mainVolume) {
      return {
        mount: mainVolume.mount,
        totalDiskSpace: mainVolume.size,
        freeDiskSpace: mainVolume.available,
      };
    }
    console.error("Main volume not found");
  } catch (error) {
    console.error("Error getting disk space:", error);
  }
  return { mount: "Unknown", totalDiskSpace: 0, freeDiskSpace: 0 };
}
```

The `systeminformation` `fsSize` function also doesn't properly account for the same device being used for multiple subvolumes:

```
  function parseDf(lines) {
    let data = [];
    lines.forEach(function (line) {
...
          if (!data.find(el => (el.fs === fs && el.type === fsType))) {
            data.push({
              fs,
              type: fsType,
              size,
              used,
              available,
              use,
              mount,
              rw
            });
          }
        }
      }
...
    return data;
  }
```

You can see it only includes the first match for a given fs device and fs type. So in my case, it doesn't even know my home directory exists.

### PR DESCRIPTION
**Pull request by fbricon**
Use [check-disk-space ](https://www.npmjs.com/package/check-disk-space) library to check disk space on `~`. 
Also fixed checking required space when model is already present.

Fixes https://github.com/Granite-Code/granite-code/issues/58

### CODE REVIEW

File: extensions/vscode/src/granite/utils/sysUtils.ts [hunk 1]
```diff
@@ -16,20 +17,12 @@ export function getSystemCPUs() {
...
-    );
-    if (mainVolume) {
-      return {
-        mount: mainVolume.mount,
-        totalDiskSpace: mainVolume.size,
-        freeDiskSpace: mainVolume.available,
-      };
-    }
-    console.error("Main volume not found");
+    const ds = await checkDiskSpace(os.homedir());
```
Comment (halfline) [inline extensions/vscode/src/granite/utils/sysUtils.ts:20]: is os.homedir() right for ollama on windows ? I guess it probably is, but just checking. This function looks much nicer!

File: gui/src/granite/GraniteWizard.tsx [hunk 2]
```diff
@@ -1,38 +1,33 @@
...
+  useContext,
+  useEffect,
+  useRef,
+  useState,
+} from "react";
+import { VSCodeButton } from "../components/VSCodeButton";
 import { DiagnosticMessage } from "./DiagnosticMessage";
+import { ProgressBlock } from "./ProgressBlock";
+import { StatusCheck } from "./StatusCheck";
+import { vscode } from "./utils/vscode";
```
Comment (halfline) [inline gui/src/granite/GraniteWizard.tsx:30]: This part of the diff is hard to read because you're moving a bunch of stuff around and I guess maybe dropping unnecessary code? It doesn't seem all the relevant to the change at hand, so probably shouldn't be in the same commit. Can you split it out?

File: gui/src/granite/GraniteWizard.tsx [hunk 3]
```diff
@@ -428,8 +428,8 @@ const ModelSelectionStep: React.FC<StepProps> = (props) => {
 
   useEffect(() => {
     if (systemInfo && systemInfo.diskSpace) {
-      const { freeDiskSpace } = systemInfo.diskSpace;
-      const requiredDiskSpace = getRequiredSpace(selectedModel);
+      let { freeDiskSpace } = systemInfo.diskSpace;
```
Comment (halfline) [inline gui/src/granite/GraniteWizard.tsx]: why did you change this to `let`?

File: gui/src/granite/GraniteWizard.tsx [hunk 4]
```diff
@@ -115,7 +112,9 @@ export const WizardProvider: React.FC<WizardProviderProps> = ({ children }) => {
   const [serverStatus, setServerStatus] = useState<ServerStatus>(
     ServerStatus.unknown,
   );
-  const [modelStatus, setModelStatus] = useState<StatusValue>("missing");
+  const [modelStatuses, setModelStatuses] = useState<Map<string, ModelStatus>>(
+    new Map(),
+  );
```
Comment (halfline) [inline gui/src/granite/GraniteWizard.tsx]: fwiw, the word statuses looks clunky to me. I realize it's a valid word and there's prior art in the code, but... `setModelStatuses` to me could mean there is more than one status for one model, while `setModelStatus` could mean one status for one model or one status for each model. So I actually like the old name better. another idea is `statusByModel` and `setStatusByModel`

anyway, it's fine as is, it just doesn't quite read smoothly to me, so I thought I'd point it out in case you agree.

File: gui/src/granite/StatusCheck.tsx [hunk 5]
```diff
@@ -1,7 +1,6 @@
 import {
   VscArrowCircleDown,
   VscCircleLarge,
-  VscCircleLargeFilled,
```
Comment (halfline) [inline gui/src/granite/StatusCheck.tsx]: unrelated change

File: gui/src/granite/GraniteWizard.tsx [hunk 6]
```diff
@@ -824,15 +826,20 @@ const WizardContent: React.FC = () => {
...
     selectedModel === "large"
       ? DEFAULT_MODEL_GRANITE_LARGE
       : DEFAULT_MODEL_GRANITE_SMALL;
   const models: string[] = [graniteModel.model, "nomic-embed-text:latest"];
-  return models.reduce((sum, model) => {
-    const modelInfo = DEFAULT_MODEL_INFO.get(model); //FIXME get from registry
-    return sum + (modelInfo ? modelInfo.size : 0);
-  }, 0);
+  const reqSpace = models
+    .filter((model) => modelStatuses.get(model) === ModelStatus.missing)
```
Comment (halfline) [inline gui/src/granite/GraniteWizard.tsx]: so this part should probably be a separate commit too. maybe the pr could be 3 commits:

1. one that cleans up and rearranges imports
2. one that switches over to looking at home directory instead of system volume
3. one that removes already downloaded models from the required space computation.

**Review by halfline — APPROVED** [review]
looks great.

File: extensions/vscode/src/granite/utils/sysUtils.ts (hunk 1 above)
Comment (fbricon) [reply extensions/vscode/src/granite/utils/sysUtils.ts:20]: yes it should work

File: gui/src/granite/GraniteWizard.tsx (hunk 2 above)
Comment (fbricon) [reply gui/src/granite/GraniteWizard.tsx:30]: done

File: gui/src/granite/GraniteWizard.tsx (hunk 4 above)
Comment (fbricon) [reply gui/src/granite/GraniteWizard.tsx]: renamed to statusByModel / setStatusByModel

File: gui/src/granite/GraniteWizard.tsx (hunk 6 above)
Comment (fbricon) [reply gui/src/granite/GraniteWizard.tsx]: done

**Comment by halfline** [comment]
looks great. the only thing i would do is better commit messages:

for example:

```commit 626a353fa77f5c69534a1d365b8432ab5973e15d (HEAD -> fix-diskspace-check)
Author: Fred Bricon <fbricon@gmail.com>
Date:   Tue Mar 11 11:18:24 2025 +0100

    gui: Deduct existing models from diskspace needs
    
    The setup wizard reports to the user if there is insufficent
    diskspace to download the Granite model the user has selected.
    
    If there is insufficient diskspace to proceed it stops the
    user from continuing.
    
    Unfortunately, there is a oversight in the code where it fails
    to consider that the user may already have a model downloaded.
    
    In that case, the model doesn't need new diskspace.
    
    This commit fixes that problem by reporting the download status
    of each model to the wizard and then ignoring already downloaded
    models when calculating diskspace needs.
    
    Signed-off-by: Fred Bricon <fbricon@gmail.com>

commit 922d0f84568401dfd2603bb2fc585e946091fbb9
Author: Fred Bricon <fbricon@gmail.com>
Date:   Tue Mar 11 10:52:26 2025 +0100

    gui: Fix disk space calculation on some platforms
    
    The setup wizard needs to know how much disk is available
    on the user's system so it can inform the user if there
    is insufficient disk space to download the (rather large)
    Granite models.
    
    The code currently does this using the systeminformation
    module to check the available space on the root filesystem.
    
    That isn't exactly correct, though, because models are
    stored in the users directory, which may be on a different
    filesystem altogether.
    
    Furthermore, systeminformation doesn't handle btrfs systems
    properly, since it keys output off the volume name, and the
    volume name is shared between subvolumes with btrfs.
    
    This commit addresses both problems by switching the code
    over to use the check-disk-space module, which is more
    form fit for our purposes anyway.
    
    Signed-off-by: Fred Bricon <fbricon@gmail.com>

commit 4d9a4b484e309b630e1ac081b7e5d0243f6b99c6
Author: Fred Bricon <fbricon@gmail.com>
Date:   Tue Mar 11 10:20:18 2025 +0100

    gui: Fix code formatting with prettier
    
    There are some minor style problems in the
    setup wizard related code.
    
    - Some of the imports are in the wrong order
    - Not all lines wrap properly
    
    This commit addresses those problems by running
    the code through Prettier and letting it figure
    it out.
    
    Signed-off-by: Fred Bricon <fbricon@gmail.com>
```

but feel free to merge whenever
